# Generated by Django 4.2.6 on 2023-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
