# Generated by Django 4.2.6 on 2023-12-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots_app', '0003_remove_candidate_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
