# Generated by Django 4.2.6 on 2023-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots_app', '0004_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
