# Generated by Django 4.2.6 on 2023-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots_app', '0005_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
