# Generated by Django 4.2.6 on 2023-12-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ots_app', '0006_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
